[workspace]
resolver = "2"
members = ["naga-interpreter", "wgpu-cpu", "wgpu-cpu-tests"]

[patch.crates-io]
wgpu = { path = "../wgpu/wgpu" }
naga = { path = "../wgpu/naga" }
approx = { git = "https://github.com/jgraef/approx.git", branch = "array" }
